#!/usr/bin/env bash

echo "Parameter arg: $1"


# ========= variable ============
DATE_NOW=$(date '+%d/%m/%Y %H:%M:%S')

#
OSNAME=`perl ../agent/get_os.pl`
OSVERSION=""
if [[ "${OSNAME}" == "centos" ]] ;then
  OSNAME="CentOS"
  OSVERSION=`rpm -q --queryformat '%{VERSION}' centos-release`
elif [[ "${OSNAME}" == "redhat" ]]; then
  OSNAME="RedHat"
  OSVERSION=`rpm -q --queryformat '%{VERSION}' epel-release`
elif [[ "${OSNAME}" == "cloudlinux" ]]; then
  OSNAME="CloudLinux"
  OSVERSION=`rpm -q --queryformat '%{VERSION}' epel-release`
else
  echo "${red}Error : Operating system is not support.${reset}"
  echo "${red}OS : ${OSNAME}${reset}"
  exit;
fi

copy_to_ezydir()
{
  mkdir -p /usr/local/ezyadmin
  cd /usr/local/ezyadmin
  cp -af ../agent /usr/local/ezyadmin/
}

setup_linux()
{
  echo "Setup Patch Manager for linux ..."
  # 1. dependency
  
  # 2. install connector


  echo "$DATE_NOW" > /usr/local/ezyadmin/agent/linux
}
setup_cpanel()
{
  echo "Setup Patch Manager for linux ..."
  echo "$DATE_NOW" > /usr/local/ezyadmin/agent/cpanel
}
setup_da()
{
  echo "Setup Patch Manager for linux ..."
  echo "$DATE_NOW" > /usr/local/ezyadmin/agent/da
}
setup_cloudLinux()
{
  echo "Setup Patch Manager for linux ..."
  echo "$DATE_NOW" > /usr/local/ezyadmin/agent/cloudLinux
}