#!/usr/bin/env bash

echo "Parameter arg: $1"
INPUTKEY=$1

# ========= variable ============
DATE_NOW=$(date '+%d/%m/%Y %H:%M:%S')

#
OSNAME=`perl ../agent/get_os.pl`
OSVERSION=""
if [[ "${OSNAME}" == "centos" ]] ;then
  OSNAME="CentOS"
  OSVERSION=`rpm -q --queryformat '%{VERSION}' centos-release`
elif [[ "${OSNAME}" == "redhat" ]]; then
  OSNAME="RedHat"
  OSVERSION=`rpm -q --queryformat '%{VERSION}' epel-release`
elif [[ "${OSNAME}" == "cloudlinux" ]]; then
  OSNAME="CloudLinux"
  OSVERSION=`rpm -q --queryformat '%{VERSION}' epel-release`
else
  echo "${red}Error : Operating system is not support.${reset}"
  echo "${red}OS : ${OSNAME}${reset}"
  exit;
fi

copy_to_ezydir()
{
  mkdir -p /usr/local/ezyadmin
  cd /usr/local/ezyadmin
  cp -af ../agent /usr/local/ezyadmin/
}

setup_linux()
{
  echo "Setup Patch Manager for linux ..."
  # 1. dependency
  
  # 2. install connector


  echo "$DATE_NOW" > /usr/local/ezyadmin/agent/linux
}
setup_cpanel()
{
  echo "Setup Patch Manager for linux ..."
  echo "$DATE_NOW" > /usr/local/ezyadmin/agent/cpanel
}
setup_da()
{
  echo "Setup Patch Manager for linux ..."
  echo "$DATE_NOW" > /usr/local/ezyadmin/agent/da
}
setup_cloudLinux()
{
  echo "Setup Patch Manager for linux ..."
  echo "$DATE_NOW" > /usr/local/ezyadmin/agent/cloudLinux
}

Check_Support()
{
  echo "${green}------------- Check support -------------${reset}"
  # TMP_YUM=`which yum 2> /dev/null` || TMP_YUM=$?
  TMP_YUM=`yum -v 2> /dev/null` || TMP_YUM=$?
  if [ "${TMP_YUM}x" == "x" ] || [ "${TMP_YUM}" == "127" ]; then
    echo "${red}Error : Operating system is not support.${reset}"
    exit;
  fi
  echo "${green}TMP_YUM ${TMP_YUM}="

  OSNAME=`perl ../agent/get_os.pl`
  OSVERSION=""
  if [[ "${OSNAME}" == "centos" ]] ;then
    OSNAME="CentOS"
    OSVERSION=`rpm -q --queryformat '%{VERSION}' centos-release`
  elif [[ "${OSNAME}" == "redhat" ]]; then
    OSNAME="RedHat"
    OSVERSION=`rpm -q --queryformat '%{VERSION}' epel-release`
  elif [[ "${OSNAME}" == "cloudlinux" ]]; then
    OSNAME="CloudLinux"
    OSVERSION=`rpm -q --queryformat '%{VERSION}' epel-release`
  else
    echo "${red}Error : Operating system is not support.${reset}"
    echo "${red}OS : ${OSNAME}${reset}"
    exit;
  fi
}

setup_respo6()
{
  cp -af ../config/fusioninventory.repo_v6 /etc/yum.repos.d/ez_fusioninventory.repo
  yum -y install fusioninventory-agent fusioninventory-agent-task-inventory
}

setup_respo7()
{
  cp -af ../config/fusioninventory.repo_v7 /etc/yum.repos.d/ez_fusioninventory.repo
  yum -y install fusioninventory-agent fusioninventory-agent-task-inventory
}

setup_respo8()
{
  subscription-manager repos --enable "codeready-builder-for-rhel-8-$(arch)-rpms"
  dnf config-manager --set-enabled PowerTools
  dnf install fusioninventory-agent fusioninventory-agent-task-inventory
}

setup_respo()
{
  if [[ "${OSVERSION}" -lt "6" ]] ;then
    echo "${red}Error : Operating system is not support.${reset}"
    echo "${red}OS : ${OSNAME} ${OSVERSION}${reset}"
    exit;
  elif [[ "${OSVERSION}" -eq "6" ]]; then
    setup_respo6
  elif [[ "${OSVERSION}" -eq "7" ]]; then
    setup_respo7
  else
    echo "${red}Error : Operating system is not support.${reset}"
    echo "${red}OS : ${OSNAME}${reset}"
    echo "Please concact us."
    exit;
  fi
}

# ========== main ==============
Check_Support
setup_respo 

