#!/usr/bin/env bash

#use
#./ezy_core.sh > ci_${HOSTNAME}.json && curl -H "Content-Type: application/json" -X POST --data-binary @ci.json http://192.168.100.80:8888/inventories/agent

#./ezy_core.sh > ezy_core.json
# curl -H "Content-Type: application/json" -X POST --data-binary @ci_cpdev1.rvglobalsoft.net.json http://192.168.100.80:8888/inventories/agent?org=551a483d973ce19219324585

#How to make yum show installed & latest packages (CentOS)

#TODO
#Notification incident

#http://arstechnica.com/civis/viewtopic.php?t=1081335

#get version
#http://unix.stackexchange.com/questions/54987/how-to-know-centos-version
 
#echo \"package name\",\"current version\",\"update version\"

#installl dependency
#cpan Linux::Distribution YAML

#================== function =============================
trim() {
    # Determine if 'extglob' is currently on.
    local extglobWasOff=1
    shopt extglob >/dev/null && extglobWasOff=0 
    (( extglobWasOff )) && shopt -s extglob # Turn 'extglob' on, if currently turned off.
    # Trim leading and trailing whitespace
    local var=$1
    var=${var##+([[:space:]])}
    var=${var%%+([[:space:]])}
    (( extglobWasOff )) && shopt -u extglob # If 'extglob' was off before, turn it back off.
    echo -n "$var"  # Output trimmed string.
}
#================== function =============================

#================== variable ========================

#OSNAME=`perl -e ' use Linux::Distribution qw(distribution_name distribution_version);  my $linux = Linux::Distribution->new;if(my $distro = $linux->distribution_name()) { my $version = $linux->distribution_version();print "$distro";}'`
OSNAME=`perl /usr/local/ezyadmin/agent/get_os.pl`
OSVERSION=""
if [[ "${OSNAME}" == "centos" ]] ;then
	OSNAME="CentOS"
	OSVERSION=`rpm -q --queryformat '%{VERSION}' centos-release`
elif [[ "${OSNAME}" == "redhat" ]]; then
	OSNAME="RedHat"
	OSVERSION=`rpm -q --queryformat '%{VERSION}' epel-release`
elif [[ "${OSNAME}" == "cloudlinux" ]]; then
	OSNAME="CloudLinux"
	OSVERSION=`rpm -q --queryformat '%{VERSION}' epel-release`
else
	echo "Not support os : ${OSNAME}"
	exit;
fi

if [[ "${OSVERSION}" == "package centos-release is not installed" ]]
then
	OSVERSION=`cat /etc/redhat-release | tr '\n' ' ' | sed -e 's/[^\ +0-9\.]/ /g' -e 's/^ *//g' -e 's/ *$//g' | awk -F \. {'print $1'}`
fi

OSARCH=`uname -m`
ALLMONITORBY="[\"${OSNAME}${OSVERSION}\""

CPNAME="none"
TIER=""

#==============cpanel================
FILE_Cpanel="/etc/cpupdate.conf"
if [ -f $FILE_Cpanel ];
then
	CPNAME="cpanel"
	TIER=`grep CPANEL /etc/cpupdate.conf`
	TIER=${TIER##*\=}
	
	CPVERSION=`/usr/local/cpanel/cpanel -V`
	
fi



#=================general data===============
HOSTNAME=`hostname -f`
echo "{"
echo "\"agent\" : \"agent\","
echo "\"patch_for\" : \"linux\","
echo "\"connector_id\" : \"5e0307987f0fc331388ff450\","
echo "\"osarch\" : \"${OSARCH}\","
echo "\"osname\" : \"${OSNAME}\","
echo "\"hostname\" : \"${HOSTNAME}\","
echo "\"osversion\" : \"${OSVERSION}\","
echo "\"cpname\" : \"${CPNAME}\","
echo "\"tier\" : \"${TIER}\","

echo "\"ci\" : [ {} "

#========================yum==============================
<<COMMENT_YUM
#use inventory agent 
yum -q list installed | tr "\n" "#" | sed -e 's/# / /g' | tr "#" "\n"  | while read i
do
    i=$(echo $i) #this strips off yum's irritating use of whitespace
    if [ "${i}x" != "x" ]
    then
        UVERSION=${i#*\ }
        UVERSION=${UVERSION%\ *}
        PNAME=${i%%\ *}
        PNAME=${PNAME%.*}
        ARCH=${i%%\ *}
        ARCH=${ARCH##*.}
        FNAME=${i%%\ *}
        REPO=${i#*\ }
        REPO=${REPO#*\ }
        
        #clean version x:xx.xx
		if [[ $UVERSION == *":"* ]]
		then
			UVERSION=${UVERSION##*:}
		fi
		
        #echo "${REPOS}";
        #echo $(rpm -q "${PNAME}" --qf '"%{NAME}","%{VERSION}","')${UVERSION}\"
		echo ",{ \"name\" : \"${PNAME}\" ,  \"fullname\" : \"${FNAME}\" , \"latestversion\" : \"${UVERSION}\" , \"arch\" : \"${ARCH}\" , \"from\" : \"rpm\" ,\"repo\" : \"${REPO}\" , \"osname\" : \"${OSNAME}\", \"osversion\" : \"${OSVERSION}\", \"osarch\" : \"${OSARCH}\"} "
		#if [[ "${REPOS}" =~ ^(base|epel|extras|updates|@updates)$ ]]; then
			#	#echo "valid action"
		#fi
    fi
done
#echo "]"
COMMENT_YUM

#===================3rdinstallation==============================
#==========pear============
#PEAR=`which pear`
#http://askubuntu.com/questions/29370/how-to-check-if-a-command-succeeded

#TMP_PEAR=""
TMP_PEAR=`which pear 2> /dev/null` || TMP_PEAR=$?
if [ "${TMP_PEAR}x" != "x" ] ; then
	ALLMONITORBY="${ALLMONITORBY},\"thirdparty_pear\""
	#echo "\"ci\" : [ {} "
	#pear list-all | tr "\n" "#" | sed -e 's/# / /g' | tr "#" "\n" | while read i j 
	#pear list | while read i j k
	#eval "$TMP_PEAR list" | while read i j k
  eval ${TMP_PEAR} list 2> /dev/null | while read i j k
	do
		i=$(echo $i)
		j=$(echo $j)
		
		if [ "${i}x" != "x" ] && [ "${i}" != "INSTALLED" ]  && [ "${i}" != "PACKAGE" ] &&  [ "${j}x" != "x" ] && [[ $j =~ ^[0-9]{1} ]] ; then
	    	echo ",{\"name\":\"${i}\",\"fullname\":\"${i}\",\"version\":\"${j}\",\"from\":\"pear\",\"osname\":\"${OSNAME}\",\"osversion\":\"${OSVERSION}\",\"osarch\":\"${OSARCH}\",\"monitorby\":\"thirdparty_pear\" , \"managedby\":\"thirdparty\"}";
		fi
    done
    #echo "]"
fi
#==========cpan============
#which cpan
#TMP_CPAN=""
TMP_CPAN=`which cpan 2> /dev/null` || TMP_CPAN=$?
if [ "${TMP_CPAN}x" != "x" ] ; then
	ALLMONITORBY="${ALLMONITORBY},\"thirdparty_cpan\""
	#TODO Fix cpan run command is frist
	cpan -O 2> /dev/null | while read i j k
	do
		i=$(echo $i)
		j=$(echo $j)
		k=$(echo $k)
		
		if [ "${i}x" != "x" ] && [ "${i}" != "INSTALLED" ]  && [ "${i}" != "PACKAGE" ] &&  [ "${j}x" != "x" ] && [[ $j =~ ^[0-9]{1} ]] && [[ $k =~ ^[0-9]{1} ]] ; then
	    	echo ",{\"name\":\"${i}\",\"fullname\":\"${i}\",\"version\":\"${j}\",\"from\":\"cpan\",\"osname\":\"${OSNAME}\",\"osversion\":\"${OSVERSION}\",\"osarch\":\"${OSARCH}\",\"monitorby\":\"thirdparty_cpan\", \"managedby\":\"thirdparty\"}";
	    fi
    done
    #echo "]"
fi

#=================== kernel is not managed by yum =========================
KMANAGEDBY="package"
KFROM="rpm"
KEFFECTIVE_VERSION=`uname -r`
KEFFECTIVE_VERSION=${KEFFECTIVE_VERSION%.*}
KARCH=`uname -m`
K_VERSION=""
#kernel install last
#rpm -qa kernel | while read k
rpm -q kernel --qf "%{NAME}   %{VERSION}-%{RELEASE}\n" | while read k v
do
	k=$(echo $k)
	v=$(echo $v)
    if [ "${k}x" != "x" ] && [ "${v}x" != "x" ] ; then
    	K_VERSION="$v"
    	#echo ",{\"name\":\"${k}\",\"fullname\":\"${k}\",\"version\":\"${v}\",\"comments\":\"The Linux kernel\",\"from\":\"kernel\",\"osname\":\"${OSNAME}\",\"osversion\":\"${OSVERSION}\",\"osarch\":\"${OSARCH}\",\"monitorby\":\"kernel\"}"
    fi
done

#KernelCare =====================
Path_KernelCareCtl="/usr/bin/kcarectl"
if [ -f $Path_KernelCareCtl ];
then
	
	#SW_NAME="kernelcare"a
	#SW_VERSION=`/usr/bin/kcarectl --version`
	#SW_COMMENT=`rpm -q --queryformat '%{SUMMARY}' kernelcare`
	#echo ",{\"name\":\"${SW_NAME}\",\"fullname\":\"${SW_NAME}\",\"version\":\"${SW_VERSION}\",\"comments\":\"${SW_COMMENT}\",\"from\":\"kernel\",\"osname\":\"${OSNAME}\",\"osversion\":\"${OSVERSION}\",\"osarch\":\"${OSARCH}\",\"monitorby\":\"kernel\"}"
	
	#KEFFECTIVE_VERSION=`/usr/bin/kcarectl --uname`
  KCARE_V=`kcarectl --uname 2> /dev/null`
	# KEFFECTIVE_VERSION=`kcarectl --uname 2> /dev/null`
  if [ "${KCARE_V}x" != "x" ];then
    KMANAGEDBY="kernel"
    KFROM="kernel"
    KEFFECTIVE_VERSION="$KCARE_V"
  fi 
fi

#Ksplice ===========================
KTMM=`rpm -q ksplice-uptrack-release --qf "%{NAME}"`
KTMM=$(echo $KTMM)
if [ "${KTMM}x" != "KTMM" ] && [ "${KTMM}" == "ksplice-uptrack-release" ]
then
	# KMANAGEDBY="kernel"
  # KFROM="kernel"
	# KEFFECTIVE_VERSION=`uptrack-uname -r 2> /dev/null`
  KSP_V=`uptrack-uname -r 2> /dev/null`
  if [ "${KSP_V}x" != "x" ];then
    KMANAGEDBY="kernel"
    KFROM="kernel"
    KEFFECTIVE_VERSION="$KSP_V"
  fi 
fi	

KMONITORBY="${OSNAME}${OSVERSION}"
TestCloudLinux=$(echo $KEFFECTIVE_VERSION | grep lve)
if [ "${TestCloudLinux}x" != "x" ];then
	KMONITORBY="$CLOUNDLINUX_MONITOR"
fi	

#Effective kernel version
echo ",{\"name\":\"kernel\",\"fullname\":\"kernel.${KARCH}\",\"version\":\"${KEFFECTIVE_VERSION}\",\"effective_version\":\"${KEFFECTIVE_VERSION}\",\"lastupdate_version\":\"${K_VERSION}\",\"comments\":\"The Linux kernel\",\"from\":\"${KFROM}\",\"osname\":\"${OSNAME}\",\"osversion\":\"${OSVERSION}\",\"osarch\":\"${OSARCH}\",\"monitorby\":\"${KMONITORBY}\",\"managedby\":\"${KMANAGEDBY}\"}"

#list software managed kernel
yum list installed | egrep 'uptrack|ksplice|kernelcare' | tr "\n" "#" | sed -e 's/# / /g' | tr "#" "\n"  | while read i
do
    i=$(echo $i) #this strips off yum's irritating use of whitespace
    if [ "${i}x" != "x" ]
    then
        UVERSION=${i#*\ }
        UVERSION=${UVERSION%\ *}
        PNAME=${i%%\ *}
        PNAME=${PNAME%.*}
        ARCH=${i%%\ *}
        ARCH=${ARCH##*.}
        FNAME=${i%%\ *}
        REPO=${i#*\ }
        REPO=${REPO#*\ }
        
        #clean version x:xx.xx
		if [[ $UVERSION == *":"* ]]
		then
			UVERSION=${UVERSION##*:}
		fi
		
		COMMENT=`rpm -q --queryformat '%{SUMMARY}' ${PNAME}`
		TKMONITORBY="${OSNAME}${OSVERSION}"
		echo ",{\"name\":\"${PNAME}\",\"fullname\":\"${FNAME}\",\"version\":\"${UVERSION}\",\"comments\":\"${COMMENT}\",\"from\":\"rpm\",\"osname\":\"${OSNAME}\",\"osversion\":\"${OSVERSION}\",\"osarch\":\"${OSARCH}\",\"monitorby\":\"${TKMONITORBY}\",\"managedby\":\"kernel\"}"
    fi
done

#===================end==============================
echo "],"

#=======================================exclude package for yum====================================
script -q -c "yum list installed -d3" ezytmp_yum.txt > /dev/null
echo "\"exclude\" : [ {} "
grep "\[31m" ezytmp_yum.txt | tr "\n" "#" | sed -e 's/# / /g' | tr "#" "\n" | while read i

do
	i=$(echo $i)
	if [ "${i}x" != "x" ] && [[ "$i" =~ \[31m ]]
    then
    	i=$(echo $i | sed -r "s/\x1B\[([0-9]{1,2}(;[0-9]{1,2})?)?[m|K]//g")
        #UVERSION=${i#*\ }
        #UVERSION=${UVERSION%\ *}
        PNAME=${i%%\ *}
        PNAME=${PNAME%.*}
        #ARCH=${i%%\ *}
        #ARCH=${ARCH##*.}
        #FNAME=${i%%\ *}
        #REPO=${i#*\ }
        #REPO=${REPO#*\ }
		#echo ",{ \"name\" : \"${PNAME}\" ,  \"fullname\" : \"${FNAME}\" , \"latestversion\" : \"${UVERSION}\" , \"arch\" : \"${ARCH}\" , \"from\" : \"rpm\" ,\"repo\" : \"${REPO}\" , \"osname\" : \"${OSNAME}\", \"osversion\" : \"${OSVERSION}\", \"osarch\" : \"${OSARCH}\"} "
		echo ",{ \"name\" : \"${PNAME}\"} "
    fi
done
echo "],"
#===================end==============================

#================================== get all managedby===================================
echo "\"allmonitorby\" : ${ALLMONITORBY}]"
#================================== end get all managedby===============================
echo "}"
exit;