#!/usr/bin/env bash

# How to make yum show installed & latest packages (CentOS)

# TODO
# Notification incident

# http://arstechnica.com/civis/viewtopic.php?t=1081335

# get version
# http://unix.stackexchange.com/questions/54987/how-to-know-centos-version

#installl dependency

#================== function =============================
trim() {
    # Determine if 'extglob' is currently on.
    local extglobWasOff=1
    shopt extglob >/dev/null && extglobWasOff=0 
    (( extglobWasOff )) && shopt -s extglob # Turn 'extglob' on, if currently turned off.
    # Trim leading and trailing whitespace
    local var=$1
    var=${var##+([[:space:]])}
    var=${var%%+([[:space:]])}
    (( extglobWasOff )) && shopt -u extglob # If 'extglob' was off before, turn it back off.
    echo -n "$var"  # Output trimmed string.
}
#================== function =============================

#================== variable ========================

OSNAME=`perl -e ' use Linux::Distribution qw(distribution_name distribution_version);  my $linux = Linux::Distribution->new;if(my $distro = $linux->distribution_name()) { my $version = $linux->distribution_version();print "$distro";}'`
OSVERSION=""
if [[ "${OSNAME}" == "centos" ]] ;then
	OSNAME="CentOS"
	OSVERSION=`rpm -q --queryformat '%{VERSION}' centos-release`
elif [[ "${OSNAME}" == "redhat" ]]; then
	OSNAME="RedHat"
	OSVERSION=`rpm -q --queryformat '%{VERSION}' epel-release`
else
	echo "Not support os : ${OSNAME}"
	exit;
fi

if [[ "${OSVERSION}" == "package centos-release is not installed" ]]
then
	OSVERSION=`cat /etc/redhat-release | tr '\n' ' ' | sed -e 's/[^\ +0-9\.]/ /g' -e 's/^ *//g' -e 's/ *$//g' | awk -F \. {'print $1'}`
fi

OSARCH=`uname -m`
ALLMONITORBY=""

CPNAME="none"
TIER=""

#==============cpanel================
FILE_Cpanel="/etc/cpupdate.conf"
if [ -f $FILE_Cpanel ];
then
	CPNAME="cpanel"
	TIER=`grep CPANEL /etc/cpupdate.conf`
	TIER=${TIER##*\=}
	
	CPVERSION=`/usr/local/cpanel/cpanel -V`
	
fi

#=================general data===============
HOSTNAME=`hostname -f`
echo "{"
echo "\"agent\" : \"agent\","
echo "\"patch_for\" : \"cpanel\","
echo "\"connector_id\" : \"5c74c7ef3ae4f52ae9e1833c\","
echo "\"osarch\" : \"${OSARCH}\","
echo "\"osname\" : \"${OSNAME}\","
echo "\"hostname\" : \"${HOSTNAME}\","
echo "\"osversion\" : \"${OSVERSION}\","
echo "\"cpname\" : \"${CPNAME}\","
echo "\"tier\" : \"${TIER}\","

echo "\"ci\" : [ {} "

#==============cpanel================
FILE_Cpanel="/etc/cpupdate.conf"
if [ -f $FILE_Cpanel ];
then	
	CPMonitorBy="cpanel_${TIER}"
	ALLMONITORBY="[\"${CPMonitorBy}\"]"
	CPManagedBy="cp"
	#cp version
	CP_VERSION=`cat /usr/local/cpanel/version`
	echo ",{ \"name\" : \"${CPMonitorBy}\" ,  \"fullname\" : \"${CPMonitorBy}\" , \"version\" : \"${CP_VERSION}\", \"monitorby\" : \"${CPMonitorBy}\", \"managedby\" : \"${CPManagedBy}\", \"cpname\" : \"cpanel\", \"cpversion\" : \"${TIER}\",  \"from\" : \"cpanel\" , \"osname\" : \"${OSNAME}\", \"osversion\" : \"${OSVERSION}\", \"osarch\" : \"${OSARCH}\"} "
	
	#easy apache
	EA_TEMP=`/usr/local/cpanel/bin/rebuild_phpconf --current | grep 'DEFAULT PHP: ea-php'`
	EA_TEMP=$(echo $EA_TEMP)
	EASYAPACHE_VERSION=""
	PHP_NAME="php"
	EASYAPACHE_NAME="easyapache"
	PHP_VERSION=""
	FTP_VERSION=""
	if [ "${EA_TEMP}x" != "x" ]; then
		EASYAPACHE_VERSION="4"
		
		#Get php version
		/usr/local/cpanel/bin/rebuild_phpconf --current | sed -e 's/^ea\-php+[0-9\.]/ /g' -e 's/^ *//g'  | awk -F \  {'print $1'} | while read eachPhp
		do
			eachPhp=$(echo $eachPhp)
			CK_FILE="/etc/scl/prefixes/${eachPhp}"
			if [ "${eachPhp}x" != "x" ] && [[ $eachPhp != DEFAULT ]]
			then
				PHP_VERSION=`scl enable $eachPhp 'php -v' | tr '\n' ' ' | sed -e 's/[^\ +0-9\.]/ /g' -e 's/^ *//g' | awk -F \  {'print $1'}`
				#echo "${eachPhp}=${PHP_VERSION}"
				PHP_DIS=${PHP_VERSION%.*}
				PHP_NAME="php$PHP_DIS"
				echo ",{ \"name\" : \"${PHP_NAME}\" ,  \"fullname\" : \"${PHP_NAME}\" , \"version\" : \"${PHP_VERSION}\", \"monitorby\" : \"${CPMonitorBy}\", \"managedby\" : \"${CPManagedBy}\", \"cpname\" : \"cpanel\" ,\"cpversion\" : \"${TIER}\",  \"from\" : \"cpanel\" , \"osname\" : \"${OSNAME}\", \"osversion\" : \"${OSVERSION}\", \"osarch\" : \"${OSARCH}\"} "
			fi
		done
		
	else
		EASYAPACHE_VERSION=`/usr/local/cpanel/scripts/easyapache --version | grep 'Easy Apache v' |  tr '\n' ' ' | sed -e 's/[^\+0-9\.]/ /g' -e 's/^ *//g'`
		PHP_VERSION=`php -v | tr '\n' ' ' | sed -e 's/[^\ +0-9\.]/ /g' -e 's/^ *//g' | awk -F \  {'print $1'}`
		
		PHP_DIS=${PHP_VERSION%.*}
		PHP_NAME="php$PHP_DIS"
		echo ",{ \"name\" : \"${PHP_NAME}\" ,  \"fullname\" : \"${PHP_NAME}\" , \"version\" : \"${PHP_VERSION}\", \"monitorby\" : \"${CPMonitorBy}\", \"managedby\" : \"${CPManagedBy}\", \"cpname\" : \"cpanel\" ,\"cpversion\" : \"${TIER}\",  \"from\" : \"cpanel\" , \"osname\" : \"${OSNAME}\", \"osversion\" : \"${OSVERSION}\", \"osarch\" : \"${OSARCH}\"} "
		
	fi
	#echo "EASYAPACHE_VERSION=${EASYAPACHE_VERSION}"
	#echo "PHP_VERSION=${PHP_VERSION}"
	echo ",{ \"name\" : \"${EASYAPACHE_NAME}\" ,  \"fullname\" : \"${EASYAPACHE_NAME}\" , \"version\" : \"${EASYAPACHE_VERSION}\", \"monitorby\" : \"${CPMonitorBy}\", \"managedby\" : \"${CPManagedBy}\", \"cpname\" : \"cpanel\" ,\"cpversion\" : \"${TIER}\",  \"from\" : \"cpanel\" , \"osname\" : \"${OSNAME}\", \"osversion\" : \"${OSVERSION}\", \"osarch\" : \"${OSARCH}\"} "
	
	#apache
	APACHE_VERSION=`httpd -v | tr '\n' ' ' | sed -e 's/[^\ +0-9\.]/ /g' -e 's/^ *//g' | awk -F \  {'print $1'}`
	APACHE_DIS=${APACHE_VERSION%.*}
	APACHE_NAME="apache$APACHE_DIS"
	#echo "APACHE_VERSION = ${APACHE_VERSION}"
	echo ",{ \"name\" : \"${APACHE_NAME}\" ,  \"fullname\" : \"${APACHE_NAME}\" , \"version\" : \"${APACHE_VERSION}\", \"monitorby\" : \"${CPMonitorBy}\", \"managedby\" : \"${CPManagedBy}\", \"cpname\" : \"cpanel\" ,\"cpversion\" : \"${TIER}\",  \"from\" : \"cpanel\" , \"osname\" : \"${OSNAME}\", \"osversion\" : \"${OSVERSION}\", \"osarch\" : \"${OSARCH}\"} "
	
	#ftp server
	FTP_NAME=`cat /var/cpanel/cpanel.config | grep ftpserver | awk -F \=  {'print $2'}`
	if [[ $FTP_NAME == pure\-ftpd ]] ; then
		FTP_VERSION=`pure-ftpd --help | head -1 | sed -e 's/[^\+0-9\.]/ /g' -e 's/^ *//g'`
	elif [[ $FTP_NAME == proftpd ]] ; then
		FTP_VERSION=`proftpd -v | sed -e 's/[^\+0-9\.]/ /g' -e 's/^ *//g'`
	fi
	
	echo ",{ \"name\" : \"${FTP_NAME}\" ,  \"fullname\" : \"${FTP_NAME}\" , \"version\" : \"${FTP_VERSION}\", \"monitorby\" : \"${CPMonitorBy}\", \"managedby\" : \"${CPManagedBy}\", \"cpname\" : \"cpanel\" ,\"cpversion\" : \"${TIER}\",  \"from\" : \"cpanel\" , \"osname\" : \"${OSNAME}\", \"osversion\" : \"${OSVERSION}\", \"osarch\" : \"${OSARCH}\"} "
	
	#mysql
	DB_NAME="MySQL"
	DB_VERSION=`mysql -V | sed -e 's/[^\+0-9\.]/ /g' -e 's/^ *//g' | awk -F \  {'print $2'}`
	DB_DIS=${DB_VERSION%.*}
	
	DB_NAME_CHECK=`mysql -V | grep -i mariadb`
	DB_NAME_CHECK=$(echo $DB_NAME_CHECK)
	if [ "${DB_NAME_CHECK}x" != "x" ]
	then
		DB_NAME="MariaDB"
	fi
	DB_NAME="$DB_NAME$DB_DIS"
	echo ",{ \"name\" : \"${DB_NAME}\" ,  \"fullname\" : \"${DB_NAME}\" , \"version\" : \"${DB_VERSION}\", \"monitorby\" : \"${CPMonitorBy}\", \"managedby\" : \"${CPManagedBy}\", \"cpname\" : \"cpanel\" ,\"cpversion\" : \"${TIER}\",  \"from\" : \"cpanel\" , \"osname\" : \"${OSNAME}\", \"osversion\" : \"${OSVERSION}\", \"osarch\" : \"${OSARCH}\"} "

	#SpamAssassin
	SPA_NAME="spamassassin"
	SPA_VERSION=`/usr/local/cpanel/3rdparty/bin/spamd -V | head -1 | sed -e 's/[^\+0-9\.]/ /g' -e 's/^ *//g'`
	echo ",{ \"name\" : \"${SPA_NAME}\" ,  \"fullname\" : \"${SPA_NAME}\" , \"version\" : \"${SPA_VERSION}\", \"monitorby\" : \"${CPMonitorBy}\", \"managedby\" : \"${CPManagedBy}\", \"cpname\" : \"cpanel\" ,\"cpversion\" : \"${TIER}\",  \"from\" : \"cpanel\" , \"osname\" : \"${OSNAME}\", \"osversion\" : \"${OSVERSION}\", \"osarch\" : \"${OSARCH}\"} "
	
fi
#===================end==============================
echo "],"

#================================== get all managedby===================================
echo "\"allmonitorby\" : ${ALLMONITORBY}"
#================================== end get all managedby===============================
echo "}"
exit;