#!/bin/sh
# chkconfig: 345 99 01
# description: Pacth manager agent monitor software
# exzyadmind: Pacth manager agent monitor software
#
### BEGIN INIT INFO
# Provides:
# Required-Start:
# Required-Stop:
# Should-Start:
# Should-Stop:
# Default-Start:
# Default-Stop:
# Short-Description:
# Description:
### END INIT INFO

# Source function library.
. /etc/rc.d/init.d/functions

exec="nohup /usr/local/ezyadmin/agent/ezyadmin_agent 0<&- &> /var/log/ezyadmind.log &"
prog="ezyadmind"
config="/etc/fusioninventory/agent.cfg"
ezyadmin_dir="/usr/local/ezyadmin/agent/"

name=`basename $0`
pid_file="/var/run/$name.pid"

[ -e /etc/sysconfig/$prog ] && . /etc/sysconfig/$prog

lockfile=/var/lock/subsys/$prog

start() {
	#OUTPUT="$(nohup /usr/local/ezyadmin/agent/ezyadmin_agent 0<&- &> /var/log/ezyadmind.log &)"
    #[ -x $exec ] || exit 5
    #[ -f $config ] || exit 6
    #echo -n $"Starting $prog: "
    # if not running, start it up here, usually something like "daemon $exec"
    #retval=$?
    #echo
    #[ $retval -eq 0 ] && touch $lockfile
    #return $retval
    
    echo -n "Starting EzyAmin Agent : "
    if [ -f $pid_file ]; then
            PID=`cat $pid_file`
            echo $prog already running : $PID
            exit 2;
    else
            #cd $SLAPD_DIR
            #daemon  ./ns-slapd $OPTIONS
            cd $ezyadmin_dir
            #daemon "$(nohup /usr/local/ezyadmin/agent/ezyadmin_agent 0<&- &> /var/log/ezyadmind.log &)"
            daemon "$(nohup /usr/local/ezyadmin/agent/ezyadmin_agent > /dev/null 2>&1&)"
            
            RETVAL=$?
            ps -ef | grep -v grep | grep "/usr/local/ezyadmin/agent/ezyadmin_agent"  | awk '{print $2}' > $pid_file
            echo
            [ $RETVAL -eq 0 ] && touch $lockfile
            return $RETVAL
    fi
}

stop() {
    #echo -n $"Stopping $prog: "
    #ps -ef | grep "/usr/local/ezyadmin/agent/ezyadmin_agent" | grep -v grep | awk '{print $2}' | xargs kill -9
    #retval=$?
    #echo
    #[ $retval -eq 0 ] && rm -f $lockfile
    #return $retval
    echo -n "Shutting down EzyAmin Agent: "
    killproc -p /var/run/ezyadmind.pid
    #killproc bash /usr/local/ezyadmin/agent/ezyadmin_agent
    echo
    # ps -ef | grep -v grep  | grep "/usr/local/ezyadmin/agent/ezyadmin_agent" | awk '{print $2}' | xargs kill -9
    rm -f $lockfile && rm -f $pid_file
    return 0
}

restart() {
    stop
    start
}

reload() {
    restart
}

force_reload() {
    restart
}

rh_status() {
    # run checks to determine if the service is running or use generic status
    # status $prog
    status $name
}

rh_status_q() {
    rh_status >/dev/null 2>&1
}


case "$1" in
    start)
        rh_status_q && exit 0
        $1
        ;;
    stop)
        rh_status_q && stop && exit 0
        $1
        ;;
    restart)
        $1
        ;;
    reload)
        # rh_status_q && exit 7
        $1
        ;;
    force-reload)
        force_reload
        ;;
    status)
        rh_status
        ;;
    condrestart|try-restart)
        rh_status_q || exit 0
        restart
        ;;
    *)
        echo $"Usage: $0 {start|stop|status|restart|condrestart|try-restart|reload|force-reload}"
        exit 2
esac
exit $?